# Generated by Django 3.2.5 on 2021-07-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dodge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dodger',
            name='id',
        ),
        migrations.AlterField(
            model_name='dodger',
            name='id_number',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
