# Generated by Django 3.2.5 on 2021-07-27 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dodge', '0002_auto_20210727_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='dodger',
            name='latest_using_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 16, 13, 19, 533605)),
        ),
    ]
