# Generated by Django 3.2.5 on 2021-07-27 16:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Dodge', '0003_dodger_latest_using_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodger',
            name='latest_using_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 16, 31, 12, 529857, tzinfo=utc)),
        ),
    ]
