# Generated by Django 3.2.5 on 2021-07-27 16:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Dodge', '0004_alter_dodger_latest_using_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('recent_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='dodger',
            name='latest_using_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 16, 44, 27, 647473, tzinfo=utc)),
        ),
    ]
