# Generated by Django 3.2.5 on 2021-07-27 16:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Dodge', '0005_auto_20210728_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='dodger',
            name='invited_code',
            field=models.CharField(default='6g1OZbvm', max_length=255),
        ),
        migrations.AlterField(
            model_name='dodger',
            name='latest_using_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 16, 58, 19, 838577, tzinfo=utc)),
        ),
    ]
