# Generated by Django 3.2.5 on 2021-07-27 17:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Dodge', '0006_auto_20210728_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='dodger',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 17, 44, 11, 563897, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='dodger',
            name='mail_addr',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dodger',
            name='valid_times',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='dodger',
            name='latest_using_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 17, 44, 11, 563868, tzinfo=utc)),
        ),
    ]
