# Generated by Django 3.2.5 on 2021-07-29 03:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Dodge', '0007_auto_20210728_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='dodger',
            name='class_name',
            field=models.CharField(default='电子通信工程1班', max_length=255),
        ),
        migrations.AddField(
            model_name='dodger',
            name='college_name',
            field=models.CharField(default='电子与信息工程学院', max_length=255),
        ),
        migrations.AddField(
            model_name='dodger',
            name='stu_id',
            field=models.CharField(default='20201249350', max_length=255),
        ),
        migrations.AlterField(
            model_name='dodger',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 29, 3, 16, 7, 734694, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dodger',
            name='latest_using_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 29, 3, 16, 7, 734662, tzinfo=utc)),
        ),
    ]
