# Generated by Django 3.2.5 on 2021-07-29 03:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Dodge', '0008_auto_20210729_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodger',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 29, 3, 29, 34, 344013, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dodger',
            name='latest_using_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 29, 3, 29, 34, 343971, tzinfo=utc)),
        ),
    ]
