# Generated by Django 3.2.5 on 2022-03-18 11:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Dodge', '0013_auto_20210908_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='dodger',
            name='instructor_name',
            field=models.CharField(default='左香草', max_length=255),
        ),
        migrations.AddField(
            model_name='dodger',
            name='secretary_name',
            field=models.CharField(default='叶玉娣', max_length=255),
        ),
        migrations.AlterField(
            model_name='dodger',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 11, 40, 25, 944836, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dodger',
            name='latest_using_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 11, 40, 25, 944795, tzinfo=utc)),
        ),
    ]
