# Generated by Django 3.2.5 on 2022-03-18 11:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Dodge', '0014_auto_20220318_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='dodger',
            name='gender',
            field=models.CharField(default='男', max_length=255),
        ),
        migrations.AlterField(
            model_name='dodger',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 11, 50, 16, 470618, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dodger',
            name='latest_using_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 11, 50, 16, 470578, tzinfo=utc)),
        ),
    ]
