# Generated by Django 3.2.5 on 2022-03-18 11:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Dodge', '0015_auto_20220318_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='dodger',
            name='major',
            field=models.CharField(default='计算机科学与技术', max_length=255),
        ),
        migrations.AlterField(
            model_name='dodger',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 11, 52, 40, 374241, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dodger',
            name='latest_using_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 11, 52, 40, 374208, tzinfo=utc)),
        ),
    ]
