# Generated by Django 4.0.6 on 2022-07-25 13:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Dodge', '0016_auto_20220318_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodger',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 25, 13, 11, 14, 751364, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dodger',
            name='latest_using_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 25, 13, 11, 14, 751232, tzinfo=utc)),
        ),
    ]
