# Generated by Django 4.0.6 on 2022-09-04 06:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Dodge', '0017_alter_dodger_added_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodger',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 6, 54, 40, 439800, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dodger',
            name='latest_using_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 6, 54, 40, 439704, tzinfo=utc)),
        ),
    ]
