# Generated by Django 3.2.5 on 2021-09-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RH',
            fields=[
                ('district', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('all_data', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SLP',
            fields=[
                ('district', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('all_data', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Srads',
            fields=[
                ('district', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('all_data', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Temp2',
            fields=[
                ('district', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('all_data', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tprep',
            fields=[
                ('district', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('all_data', models.CharField(max_length=255)),
            ],
        ),
    ]
