# Generated by Django 3.2.5 on 2021-09-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_exh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rh',
            name='all_data',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='slp',
            name='all_data',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='srads',
            name='all_data',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='temp2',
            name='all_data',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tprep',
            name='all_data',
            field=models.CharField(max_length=500),
        ),
    ]
